### ISSUE TITLE
Feature Request: Support templates that requires package as a prestep

### ISSUE THREAD

**Issue by drorasaf** [aws-ia/taskcat#367]
**Describe the bug**
One of the common use cases when using cloudformation is to use lambd, when handling lambda in a code base, it is crucial to have it in 2 steps, first to use ```aws cloudformation package``` followed by ```aws cloudformation deploy ..``` Currently, taskcat throws an exception because it does not simulates or does the packaging step, although all the code is already in a s3 bucket.

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? custom template
2. Attach or link a copy of the template if possible (**remove any sensitive info**)
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Lambda Sample.
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non numberic character.
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name: LambdaRole
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaARN-${EnvName}
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: lambda-function-${EnvName}
      Description: LambdaFunction in python 3.6
      Runtime: python3.6
      Code: ../functions/source/myfunc
      Handler: myfunc.lambda_handler
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Environment:
        Variables:
          ENV:
            Fn::Sub: ${EnvName}
          TZ: UTC
```

3. Provide the parameters that you passed.  EnvName=dev
4. How did you install taskcat? (docker or pip3) pip3
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
access keys
6. Is your AWS environment configured via `aws configure`?
yes

**Expected behavior**
I expect taskcat to run the test on templates that requires package before it is able to run. (current workaround is to create a yaml file per region and uploading it manually)

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.0

**Additional context**
There are more cases where package is part of the standard pipeline.
Could be added to the stage create_stacks, there the code code be reused from the awscli that implement that part

**Comment by andrew-glenn** [comment]
Similar: #278

**Comment by andrew-glenn** [comment]
In good-faith, I believe this to be resolved. Please reopen if necessary.
