### ISSUE TITLE
changelog should contain contributor and pr link

### ISSUE THREAD

**Issue by jaymccon** [aws-ia/taskcat#513]
for release changelogs it would be great if the commits were grouped by pr, and included the authors username (if the author is not a maintainer).

And we should strip the version bump commits too.

Something like:

```
 - #507 - Remove region from url when completing url prefix [thanks to @villasv] 
  - 4955335 some commit message
  - 081d13b some other commit message
- #512 - this pr was opened by a maintainer 
  - f855a49 update pre-commit
  - b49fb3c remove codecov
```

**Comment by andrew-glenn** [comment]
@jaymccon, Something like this? I've intentionally removed '@' to reduce notification spam. 

- #512 - Template url parsing2
  - 17fa9393272ec72feabb2f6da4e76f57731c9c46 - Add better error handling and corrective code for the json.loads
  - d4debdf538b08fcf2c7bd98b657bc6128260aa7a - remove unnecessary code from tests
  - e8a801c1ceebd11bfd07e52ec79169dcbd4b1a64 - Fixes by precommit hooks
  - bf08cc3e92f0a98ed1d1e33d3ca10536b37f55ec - Modify test json generator to work with the project pathing and be more dynamic
  - 9beb22bae336ae56098e2e2be0b7e0fa93d2bf9d - Adding base for e2e negative test for TemplateURL parser
  - bebeae968434f3a593cd8681462334a19edbc947 - Test added for a bad URL
  - 0fcb5fa60fe904c4d7d0c81293157b9c99f1f457 - Change test to just run the linting
  - 421684c80154bf1e0732c7904ed41c343aeb8678 - Modified test for stackurlhelper
  - d2dd72ab6dd00c6a50a78aa33c102e291b240dc9 - Final tweaks for e2e
  - 8ce5813c543a4c5a38a3645add1a3dc8ac3a31c8 - Merge pull request #499 from gargana/template_url
  - bbaa5edfbcc4edf4701be7e8ff127e5d1a07d89d - Revert "Revert "Added new logic for template url parsing and tests""
  - 0a7f721987b63fd276501f9e7f6ee2d0b83ab485 - Merge branch 'template_url_parsing' into template_url_parsing2
- #510 - removing import_session
  - 057f86518862a59b1a1ff000ea2e241243b4d4b7 - removing import_session
- #507 - Remove region from url when computing url prefix [thanks to <at>villasv]
  - b1011e8f080bad5d0a7cec65559e3c160787d17f - Remove region from url when computing url prefix
- #506 - [ClientFactory] Accounting for imported sesssions in get_default_region
  - a2c649a573af95d7773ba83a02a2651becf87510 - Imported session
- #505 - Accurately determine the appropriate partition for an account. Closes #503
  - 24ba1ac9f082aeacda0d547092a5dfc4531a1159 - Determine actual partition
  - d66b84e4660188737035542243517639a7f86902 - Cached sessions
- #504 - Opt-in regional S3 buckets.
  - 6bb1ff1910223c752a8234f4050a72ea29744a60 - Regional Buckets
  - 00814bfcc5c5cb893df84fca28dcfaf04acdaffd - Schema updates
  - 8971b741f8165e7303aabeadf896b38c15cec82c - UUID replacing hashlib; fixing E2E.
- #502 - Remove duplicate pre-commit req [thanks to <at>gliptak]
  - 184f1b817a75a2f404b579961e41acecd47cc80f - Remove duplicate pre-commit req
- #501 - Add Python 3.8 support [thanks to <at>gliptak]
  - a1e6ea0fdf5a875bb59815aae19c7f1d73195b2b - Add Python 3.8 support
- #499 - Template url [thanks to <at>gargana]
  - 17fa9393272ec72feabb2f6da4e76f57731c9c46 - Add better error handling and corrective code for the json.loads
  - d4debdf538b08fcf2c7bd98b657bc6128260aa7a - remove unnecessary code from tests
  - e8a801c1ceebd11bfd07e52ec79169dcbd4b1a64 - Fixes by precommit hooks
  - bf08cc3e92f0a98ed1d1e33d3ca10536b37f55ec - Modify test json generator to work with the project pathing and be more dynamic
  - 9beb22bae336ae56098e2e2be0b7e0fa93d2bf9d - Adding base for e2e negative test for TemplateURL parser
  - bebeae968434f3a593cd8681462334a19edbc947 - Test added for a bad URL
  - 0fcb5fa60fe904c4d7d0c81293157b9c99f1f457 - Change test to just run the linting
  - 421684c80154bf1e0732c7904ed41c343aeb8678 - Modified test for stackurlhelper
  - d2dd72ab6dd00c6a50a78aa33c102e291b240dc9 - Final tweaks for e2e
- #498 - Revert "Added new logic for template url parsing and tests"
  - 6114d54f1e11127620cc6da225d7e46101590d11 - Revert "Added new logic for template url parsing and tests"
- #496 - Adding import_session to Boto3Cache; plus tests.
  - be2969efdafdca0616cbd25b35d18066e3dcd6e0 - Adding import_session to Boto3Cache; plus tests.
  - 1251040b4208e243fb151f95d6d0b43bfaf2aa60 - Modifying test assertion
- #495 - Fix anchors in README [thanks to <at>meckhardt]
  - 7efc9f7a69b72919a32d859e715024dbc89b01d3 - Fix anchors in README
- #493 - validation for `s3_object_acl`
  - 74f44da4994c604ea4ac075323224620f3f22a40 - validation for s3_object_acl. Fixes #492
- #485 - Add shorten_stack_name project parameter [thanks to <at>villasv]
  - feae99389491b2222c59fcdd80dcd59f5d6c2438 - Add shorten_stack_name project parameter
- #482 - Add e2e run tests
  - 9897e8508d694b7c8aaa1ee8725015203fa935d2 - Add test run to e2e
  - 1545fce42a591d9257bf92fc5f5c162ea87f9898 - Lint code
  - 3b3c252471a570c611f949f33b166026d6d16178 - Add debug flag to e2e (test run)
  - 74847d42c0e03000c584383586271cfc6bd143ce - Set Python Encoding env varible
- #481 - Added new logic for template url parsing and tests [thanks to <at>gargana]
  - f1967675cb042388a021332ebe9310bf131b3d2d - Added new logic for template url parsing and tests
  - 817aa49f58e35f175349ccadc3dd8b28505a3e0c - Adding new logic for urlparsing
  - d94013418c732608f4520728b6d4797e8c0636fb - Reduce some tests
  - b3763737f93c2e3dcfba596a34cb1de98145588d - Refined tests
  - 27bedee3efcba225dc739656c6de05c38dd0bbae - Fix regressions
  - 44deaa6a4f2c981ed5dd4e05b2681850f9851616 - Remove dangling old test templates
  - 2c0fb50e87d2ff9dcbf917eb3423efe3ff40328c - Cleanup of stack_url_helper
  - a903f2235450c2341d5a2d2f659abe056108d043 - Added support for default parameters in URL substitution
  - 6e51adf819c492e05abaeeb86af4ae4b35bd8f88 - Cleanup logic for default parameters
  - 4328a9fa125b0c1f05f7a59ec07a458e05acc335 - Adjust for PR review
