### ISSUE TITLE
Add example on using custom stack names using CFNTest class

### ISSUE THREAD

**Issue by LRuttenCN** [aws-ia/taskcat#644]
Hey there! 

I'm currently trying to run tests with custom stack names using the CFNTest class, since it is supported by the TestObj class. However, I don't quite see the best way to handle this at the moment. Would you override the CFNTest.run() or is there a smarter way to do it?

I'd like to have the custom stack names so I can do some backward compatibility testing when a new version of a template becomes available, I can 
 1. Test if it deploys properly using taskcat and 
 2. Try to create a changeset with the previous version. For this, I need the stackname (preferably a pre-defined pretty name so it's easier to integrate with codepipeline stages).  

Thanks in advance!

**Comment by andrew-glenn** [comment]
Oops. My bad. I added this functionality in #562, but never updated the valid schema to reflect it. The necessary schema changes are being tracked in #645. Should be pretty straightforward.
