### ISSUE TITLE
taskcat --profile $AWS_PROFILE test clean -> Failed to fetch stacks for region us-east-1 using profile default <class 'botocore.exceptions.NoCredentialsError'> Unable to locate credentials

### ISSUE THREAD

**Issue by tekdj7** [aws-ia/taskcat#661]
**Describe the bug**
Ran `taskcat --profile $AWS_PROFILE test clean <project-name or ALL>`.  It did not delete ANY of the CloudFormation Stacks (both successful & failed).

- Although only 2 regions enabled in the 1 test, it tried running against all (21) AWS Commercial Regions.  Got below error for all regions:
  - `[WARNING] : Failed to fetch stacks for region us-east-1 using profile default <class 'botocore.exceptions.NoCredentialsError'> Unable to locate credentials`

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? `No`
2. Attach or link a copy of the template if possible (**remove any sensitive info**) 
3. Provide the parameters that you passed. (**remove any sensitive info**)
4. How did you install taskcat? (docker or pip3) `pipx`
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat? `profile`
6. Is your AWS environment configured via `aws configure`? `yes`

**Expected behavior**
- I was expecting that it would delete the stacks in all AWS regions.  
- FYI, `taskcat --profile $AWS_PROFILE test run` works, so there's no credentials problem, but rather an issue with `taskcat --profile $AWS_PROFILE test clean` not working properly.

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version: `0.9.23`
 - Python3 Version: `3.8.7`

**Comment by andrew-glenn** [comment]
Improvements to credential handling are slated for `v1.0`
