### ISSUE TITLE
Cloudformation Python 2.7 otudated

### ISSUE THREAD

**Issue by emmarrig** [aws-ia/taskcat#739]
**Describe the bug**
The Cloudformation stack CopyLambdasStack fails to create as Lambda no longer supports Python 2.7 

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?- Quickstart
2. Attach or link a copy of the template if possible (**remove any sensitive info**) 
3. Provide the parameters that you passed. (**remove any sensitive info**) - following the workshop instructions
4. How did you install taskcat? (docker or pip3) pip3 
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat? 
6. Is your AWS environment configured via `aws configure`? 

**Expected behavior**
Be able to deploy TaskCat into my environment. 

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.30
 
 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by ricardotasso** [comment]
Hi @emmarrig! I'm trying to reproduce the issue on my side, may you let me know what quick start are you using, please?
