### ISSUE TITLE
[ERROR  ] : ProfileNotFound The config profile (default) could not be found

### ISSUE THREAD

**Issue by nowfox** [aws-ia/taskcat#740]
**Describe the bug**
When the role mode is used instead of AccessKey mode, the following errors are reported when the `taskcat test clean` command is executed.
`[ERROR  ] : ProfileNotFound The config profile (default) could not be found`
**To Reproduce**
1. Start an EC2 in IAM role mode
2. Install docker and taskcat
3. Run `taskcat test run --no-delete`,success.
4. Run `taskcat test clean MyProject`,the result:`[ERROR  ] : ProfileNotFound The config profile (default) could not be found`

**Expected behavior**
`taskcat test clean MyProject` can run successfully in IAM role mode.

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat v0.9.30
 - Python 3.7.10

**Additional context**

**Comment by andrew-glenn** [comment]
Improvements to the credential lookup process are slated for the v1.0 release.
