### ISSUE TITLE
Mismatched region OR complete lack of named test OR complete lack of .taskcat.yml gives no output at all

### ISSUE THREAD

**Issue by DarwinJS** [aws-ia/taskcat#743]
**Describe the bug**
When a test profile and a region is specified on the command line and 

1. the test profile does not have the region in it's list, taskcat just exits with no output.
2. the same is true if the test is not found
3. the same is true if the entire file .taskcat.yml is not found

Since it is doing a validation which failed, it would be helpful to emit it as an error.

**To Reproduce**
1. Do a test run on a test and specify --region with a region that is not specified in the test definition in .taskcat.yml OR specify a test name that does not exist in .taskcat.yml
2. Observe that it simply exits

**Expected behavior**
An error that says that the CLI specified region does not match any of the regions specified in the test.

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by tlindsay42** [comment]
Per our separate discussion, the error messages and documentation around these scenarios should be improved.
