### ISSUE TITLE
Taskcat basic CloudFormation resource check failing on valid resource

### ISSUE THREAD

**Issue by tlindsay42** [aws-ia/taskcat#758]
**Describe the bug**

While testing the VMware Tanzu Application Platform Quick Start for interop in GovCloud in [PR #93](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/pull/93), I received the following error indicating that Route 53 private hosted zones aren't supported in GovCloud, which is inaccurate. Afterward, I re-ran with the `--lint-disabled` parameter, and the deployment completed successfully.

```
version 0.9.31
[INFO   ] : Linting passed for file: /mnt/c/Users/trlindsa/git/quickstart-vmware-tanzu-application-platform/templates/aws-tap-entrypoint-new-vpc.template.yaml
[ERROR  ] : ---
[ERROR  ] : Linting detected issues in: /mnt/c/Users/trlindsa/git/quickstart-vmware-tanzu-application-platform/templates/aws-tap-entrypoint-existing-vpc.template.yaml
[ERROR  ] :     line 765 [3001] [Basic CloudFormation Resource Check] Invalid or unsupported Type AWS::Route53::HostedZone for resource
                                                            PrivateHostedZone in us-gov-east-1
[WARN   ] : No stacks were created... skipping cleanup.
[ERROR  ] : Lint failed with errors
```

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/
2. Attach or link a copy of the template if possible (**remove any sensitive info**) https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/main/templates/aws-tap-entrypoint-new-vpc.template.yaml
3. Provide the parameters that you passed. (**remove any sensitive info**) Same as in SwingLine CI.
4. How did you install taskcat? (docker or pip3) pip3
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat? Profile
6. Is your AWS environment configured via `aws configure`? Yes

**Expected behavior**

The taskcat basic CloudFormation resource check should not fail for valid resources.

**Screenshots**

With linting enabled, the linter failed on the resource check
![image](https://user-images.githubusercontent.com/11078689/182725757-bd4ca239-10b0-44cd-877a-7ad4ddbc0883.png)

With linting disabled, I made it through a full deploy & destroy
![image](https://user-images.githubusercontent.com/11078689/182725419-5d3c1b6d-267d-4767-bf95-9da189e6b938.png)

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357]) v0.9.31

 Note: Python Version (python3 required) 3.8.10

To find versions:
*Via taskcat*: `taskcat -V`

  ```
  taskcat -v
   _            _             _   
  | |_ __ _ ___| | _____ __ _| |_
  | __/ _` / __| |/ / __/ _` | __|
  | || (_| \__ \   < (_| (_| | |_
   \__\__,_|___/_|\_\___\__,_|\__|



  version 0.9.31
  0.9.31
  ```
*Via pip3*: `pip3 show taskcat`

  ```
  pip3 show taskcat | head -2
  Name: taskcat
  Version: 0.9.31
  ```
Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
Are you able to verify independently with cfn-lint specifying the us-gov region in question?

What version of cfn-lint?

**Comment by tlindsay42** [comment]
Whoops! Didn't know taskcat leveraged cfn-lint for that functionality. I'm able to reproduce in both us-gov-east-1 & us-gov-west-1 for cfn-lint versions 0.61.1 and 0.61.4. I'll open an issue over there when I'm back on Monday. Thanks @andrew-glenn!

```
$ cfn-lint -t ./templates/aws-tap-entrypoint-existing-vpc.template.yaml -r us-gov-west-1
E3001 Invalid or unsupported Type AWS::Route53::HostedZone for resource PrivateHostedZone in us-gov-west-1
./templates/aws-tap-entrypoint-existing-vpc.template.yaml:765:5

$ cfn-lint -t ./templates/aws-tap-entrypoint-existing-vpc.template.yaml -r us-gov-east-1
E3001 Invalid or unsupported Type AWS::Route53::HostedZone for resource PrivateHostedZone in us-gov-east-1
./templates/aws-tap-entrypoint-existing-vpc.template.yaml:765:5
```
