### ISSUE TITLE
Taskcat (Container Execution) gets an error when using QSS3BucketRegion: $[taskcat_current_region]

### ISSUE THREAD

**Issue by DarwinJS** [aws-ia/taskcat#764]
**Describe the bug**
The .taskcat.yml setting `QSS3BucketRegion: $[taskcat_current_region]` only works if deploying to us-east-1 it must be forced to `QSS3BucketRegion: us-east-1` to work when trying to deploy to any other region using taskcat CLI via the container.

This is the error received when I don't do this:

![Screen Shot 2022-09-30 at 4 43 12 PM](https://user-images.githubusercontent.com/11597190/194532300-8b51a4cb-87aa-42c9-9d2e-97cee0047d2d.png)

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?
Yes: https://github.com/aws-quickstart/quickstart-eks-gitlab

2. Attempt to install to a region other that us-east-1 with the .taskcat.yml setting `QSS3BucketRegion: $[taskcat_current_region]`

**Expected behavior**
To not fail.

**Screenshots**

![Screen Shot 2022-09-30 at 4 43 12 PM](https://user-images.githubusercontent.com/11597190/194532300-8b51a4cb-87aa-42c9-9d2e-97cee0047d2d.png)

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.33 - containerized

**Additional context**

**Comment by vsnyc** [comment]
Late post, but most likely this happened because `s3_regional_buckets` configuration wasn't set to `true`. You can place the following in your home directory to get rid of the error.

```
$ cat ~/.taskcat.yml 
general:
  s3_regional_buckets: true
```
