### ISSUE TITLE
Program breaks when there is a region with the resource not supported

### ISSUE THREAD

**Issue by MwM69** [aws-ia/taskcat#824]
I keep encountering this issue where if a resource type (any resource type within the CFN) is not supported in at least one region, TaskCat gives an error and exits out completely with a bunch of tracebacks without generating index.html or tell me which region(s) failed and why. Stacks are still deployed in regions that can be deployed, but I wouldn't know which regions they are unless I check it manually or write a script.

Can we get support for this?

**Comment by andrew-glenn** [comment]
Fixed in #826
