### ISSUE TITLE
taskcat execution fails with "Error while fetching server API version"

### ISSUE THREAD

**Issue by kkvinjam** [aws-ia/taskcat#825]
**Describe the bug**
All taskcat commands appears to fail with following error:

**Mac:**
taskcat version : 0.9.42
docker version: 26.1.4
Error:  `DockerException Error while fetching server API version: Not supported URL scheme http+docker`

**Linux:**
taskcat version : 0.9.42
docker version: 25.0.3
Error:  `[ERROR  ] : DockerException Invalid response from docker daemon: key "ApiVersion" is missing.`

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? _Custom template_
3. Attach or link a copy of the template if possible (**remove any sensitive info**) _N/A_
4. Provide the parameters that you passed. (**remove any sensitive info**) _N/A_
5. How did you install taskcat? (docker or pip3) _pip3_
6. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat? _access keys_ and _profile_ (issue seen with both)
7. Is your AWS environment configured via `aws configure`? _yes_ 

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
Resolved in 0.9.53
