### ISSUE TITLE
Add support for cfn-lint 1.x

### ISSUE THREAD

**Issue by dhutchison** [aws-ia/taskcat#838]
**Describe the bug**
The 0.x versions of cfn-lint received their final release at the end of July, and all new releases of cfn-lint are for 1.x. Attempting to install taskcat with a 1.x version of cfn-lint results in a dependency resolution error.

```
The conflict is caused by:
    The user requested cfn-lint==1.15.1
    taskcat 0.9.54 depends on cfn_lint<1.0 and >=0.72.0
```

**To Reproduce**
Install these two packages together. 

```
mkdir -p ~/temp/taskcat && cd ~/temp/taskcat/
python3 -m venv venv && source venv/bin/activate
pip install taskcat==0.9.54 cfn-lint==1.15.1
```

**Expected behavior**
Should be able to install taskcat and use the latest version of cfn-lint

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.54
 - Python Version 3.11.9

**Additional context**

**Comment by tlindsay42** [comment]
Would you be interested in submitting a pull request?

**Comment by dhutchison** [comment]
Yep - my intention was to give it a shot see if I can work out how to build/test this project once I'm back home & on my personal device. Will give it a shot this evening.
