### ISSUE TITLE
python 3.12 support

### ISSUE THREAD

**Issue by shadycuz** [aws-ia/taskcat#841]
I'm unable to run this on python 3.12, I think because of an old version of `cfn-lint`

stack trace

> /home/vscode/.cache/pypoetry/virtualenvs/cloud-radar-gKaRDtH8-py3.12/lib/python3.12/site-packages/cfnlint/formatters/__init__.py:14: in <module>
    from jschema_to_python.to_json import to_json
/home/vscode/.cache/pypoetry/virtualenvs/cloud-radar-gKaRDtH8-py3.12/lib/python3.12/site-packages/jschema_to_python/__init__.py:4: in <module>
    __version__ = VersionInfo(__package__).semantic_version().release_string()
/home/vscode/.cache/pypoetry/virtualenvs/cloud-radar-gKaRDtH8-py3.12/lib/python3.12/site-packages/pbr/version.py:495: in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
/home/vscode/.cache/pypoetry/virtualenvs/cloud-radar-gKaRDtH8-py3.12/lib/python3.12/site-packages/pbr/version.py:447: in _get_version_from_pkg_resources
    import pkg_resources
/home/vscode/.cache/pypoetry/virtualenvs/cloud-radar-gKaRDtH8-py3.12/lib/python3.12/site-packages/pkg_resources/__init__.py:2191: in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
E   AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
=============================== warnings summary ===============================

`ImpImporter` was removed in python 3.12

**Comment by andrew-glenn** [comment]
I think this is gonna be a bit more involved, based on that stack trace.

**Comment by shadycuz** [comment]
@andrew-glenn I was able to find a workaround. Apparently I just need to update setuptools to a certain version and the error goes away. 

Unfortuantly, poetry downgrades everytime I do `poetry install` but that's someone else's problem... thanks
